name: Cache Node and NPM dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file
inputs:
  node-version:
  - required: true
  - description: NodeJS version to use
  - default: 20.x
  working-dir:
  - required: false
  - description: The working directory of the application
  - default: ./

runs:
  using: composite
  steps: 
    - name: Setup NodeJS version ${{ inputs.nodeversion }}
      uses: actions/setup-node@v4
      with:
          node-version: ${{ inputs.nodeversion }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with: 
        path: ${{ inputs.working-dir }}
        key: deps-node-modules-${{ hashFiles('react-app/package-lock.json') }}

    - name: Install dependencies
      working-directory: inputs.working-dir
      run: npm ci
      shell: bash
    