name: Update NPM Dependencies
description: "Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files"
inputs:
  base-branch:
    required: false
    description: The branch used as the base for the dependency update checks
    default: main
  target-branch:
    required: false
    description: The branch from which the PR is created
    default: update-dependencies
  working-directory:
    required: true
    description: The working directory of the project to check for dependency updates
  gh-token:
    required: true
    description: Authentication token with repository access. Must have write access to contents and pull-requests
  debug: 
    required: false
    description: Whether the output debug messages to the console

runs: 
  using: node20
  main: index.js