name: 03 - Workflow Runners

on:     
    push:

jobs: 
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on Ubuntu runner"
                echo $RUNNER_OS 