name: 04 - Using Actions

on:     
    push:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Find path
              run: find . -name react-app

            - name: Install dependencies
              working-directory: react-app
              run: npm ci