name: 05 - 2 - Event Filters and Activity Types

on:     
    workflow_dispatch :
        branches:
            - main  # Restrict to changes targeting the main branch
        types:
            - closed

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Close PR
              run: echo Running whenever a PR is closed

