name: 07 - Using expressions

run-name: 07 - Using Expressions | Debug is ${{ inputs.debug && 'ON' || 'OFF'}} 

on:     
    workflow_dispatch:
        inputs: 
            debug:
                type: boolean
                default: false
    push:

jobs: 
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Dummy commit
              run: echo "Debug is set to ${{ inputs.debug }}"

            - name: Print start-up data
              if: inputs.debug == true
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"

            - name: Print when triggered from main
              if: inputs.debug == true && github.ref == 'refs/heads/main'
              run: echo "I was triggered from main"
            
            - name: Testing new property
              run: echo "Debug Mode is ${{ inputs.debug && 'ON' || 'OFF' }}"

            
