name: 09 - Using functions

on:     
    workflow_dispatch:
    #pull_request:

jobs: 
    echo-data:
        runs-on: ubuntu-latest
        steps:   
#            - name: Take a nap
#              run: sleep 20
            - name: Failed step
              run: exit 1
            - name: I will be skippped
              run: echo I will print if previous steps succeed.
            - name: I will execute
              if: ${{ failure() }}
              run: echo I will print if any previous step fails
            - name: I will execute
              if: ${{ !cancelled() }}
              run: echo I will always print, except when the workflow is cancelled.
            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo I will print if cancelled