name: 12 - Working with outputs

on:     
    workflow_dispatch:
        inputs: 
            build-status:
                type: choice
                options: [success, failure]
                default: success
        
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:   
            - name: Print GITHUB_OUTPUT path
              run: |
                echo "Value of github output: $GITHUB_OUTPUT"
            - name: Build
              id: build
              run: echo "status=${{inputs.build-status }}" >> "$GITHUB_OUTPUT"


