name: 12 - Working with outputs

on:     
    workflow_dispatch:
        inputs: 
            build-status:
                type: choice
                options: [success, failure]
                default: success
        
jobs: 
    build:
        runs-on: ubuntu-latest
        outputs:
            status: ${{ steps.build.outputs.status }}
            output1: ${{ steps.build.outputs.output1 }}
            output2: ${{ steps.mistake.outputs.output2 }}
            mistake: ${{ steps.mistake.outputs.mistake }}
        steps:   
            - name: Print GITHUB_OUTPUT path
              run: |
                echo "Value of github output: $GITHUB_OUTPUT"
            - name: Build
              id: build
              run: | 
                echo "status=${{inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo Printing file now:
                cat "$GITHUB_OUTPUT"
            - name: Step with mistake
              id: mistake
              run: | 
                echo "output2=value2" >> "$GITHUB_OUTPUT"
                echo "mistake=true" >> "$GITHUB_OUTPUT"
                echo Printing file now:
                cat "$GITHUB_OUTPUT"


    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: needs.build.outputs.status == 'success'
        steps:   
            - name: Deploy
              run: echo "Deploying as the status is ${{toJson(needs.build.outputs.status) }}"
            - name: Print outputs
              run: |
                echo "Output1: ${{ needs.build.outputs.output1 }}"
                echo "Json of mistake file: ${{ toJson(needs) }}"
                echo "Output2: ${{ needs.build.outputs.output2 }}"
                echo "Mistake: ${{ needs.build.outputs.mistake }}"