name: 13 - Using Caching

on:     
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Whether to execute cache step
            node-version:
                type: choice
                options: [18.x, 20.x, 21.x]
                default: 20.x
                description: node version

jobs: 
    build:
        runs-on: ubuntu-latest
        defaults:
            run: 
              working-directory: ./react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ inputs.node-version }}

            - name: Download cached dependencies
              id: cache
              if: inputs.use-cache == true
              uses: actions/cache@v3
              with: 
                path: react-app/node_modules
                key: deps-node-modules-${{ hashFiles('react-app/package-lock.json') }}
                restore-keys: deps-node-modules-

            - name: Check cache variable
              run: |
                echo ${{ toJson(steps.cache.outputs.cache-hit) }}
            
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Run unit tests
              run: npm run test

            - name: Building
              run: npm run build

            - name: Deploy to non-Prod
              run: echo "Deploying to nonprod"

    install-deps:
        runs-on: ubuntu-latest
        defaults:
            run: 
              working-directory: ./react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ inputs.node-version }}

            - name: Calculate cache key
              run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('react-app/package-lock.json') }}" >> $GITHUB_ENV
              
            - name: Use Cache Key
              run: echo "Cache Key is $CACHE_KEY"

            - name: Download cached dependencies
              id: cache
              if: inputs.use-cache == true
              uses: actions/cache@v3
              with: 
                path: react-app/node_modules
                key: $CACHE_KEY

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

    linting:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run: 
                working-directory: ./react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ inputs.node-version }}

            - name: Testing
              run: npm run test
  
            - name: Linting
              run: echo "Linting..."