name: 15 - Working with colors

on:     
    workflow_dispatch:

jobs: 
    include-example:
        name: ${{ matrix.color }}-${{ matrix.shape }}-${{matrix.size}}-${{matrix.opacity}}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                include:
                    - opacity: 50
                      color: red
                      shape: triangle
        steps:
            - name: Dummy step
              run: echo ${{ matrix.color }}-${{ matrix.shape }}-${{matrix.size}}-${{matrix.opacity}}