name: 16 - Working with environments

on:     
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

run-name: 16 - Working with Environments | env ${{ inputs.target-env }}

jobs: 
    echo:
        name: echo
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env: 
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo vars
              run: |
                echo "Env variable: ${{ env.my-env-value }}"