name: 16 - Working with environments

on:     
    workflow_dispatch:

jobs: 
    deploy-staging:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Deploy to staging
              run: echo "Deploying to staging.."
    e2e-tests:
        runs-on: ubuntu-latest
        environment: staging
        needs: deploy-staging
        steps:
            - name: Running tests
              run: echo "Running e2e tests.."
    deploy-prod:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: prod
        env: 
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo vars
              run: echo "Deploying to Prod.."
    
        
