name: 17 - 2 - custom-actions-js.yaml

on:
    workflow_dispatch:

run-name: 17 - 2 - Custom Actions - JS

jobs:
    dependency_update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update